### ISSUE TITLE
Only allow users from our Allowlist to create accounts 

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#29]
This as a stopgap for now, before we implement "referral only" logic. Wyt @bluquar?

**Comment by bluquar** [comment]
Seems fine. What's a good way to enforce this?

**Comment by lowellbander** [comment]
the easiest way I can think of is to hardcode a list of allowed emails in the registration logic, and raise an error if someone attempts to register with a different email address. Perhaps better to but it in an EBS environment variable so that it's quicker to add new entries!

Do you know if there's an easy way with our current set up to observe the aforementioned error if it does occur, like check a dashboard or receive an email?

**Comment by bluquar** [comment]
that makes sense! the PR I just created for registration uses username/password and does not use email address, since this was easier to do out of the box with passport. I can add email address, but I think it makes sense to push that off to v0.3+ since it's not strictly necessary for our scenarios. So maybe an allowlist of usernames for now?

I don't know how to observe that sort of error! Can you look into that please?

**Comment by lowellbander** [comment]
yep!

**Comment by lowellbander** [comment]
Will you please add me to the EBS project?

**Comment by bluquar** [comment]
sure, done! you should have an email with login info

**Comment by bluquar** [comment]
Yeah that’s a good idea. Re adding documents to the collection, the
database can only be modified through our backend because there’s only one
db user and its password is only available through our backend. So we will
have to ensure in our code that only registered users add documents
