### ISSUE TITLE
Investigate native app build failures

### ISSUE THREAD

**Issue by bluquar** [dandelion-community/aid-app-monorepo#37]

**Comment by lowellbander** [comment]
Thank you for filing this! I saw all the failures and had no idea what was happening. A few of them mentioned the CodeQL analysis and I wasn't sure what to make of it

**Comment by lowellbander** [comment]
So like here's one, looks like the build failed on my development branch because I was editing the docker file, which means this perhaps isn't something we should be emailed about? But better to have in PR than when it hits latest, right? https://github.com/dandelion-community/aid-app-monorepo/actions/runs/1580259367

**Comment by lowellbander** [comment]
Example of failure relating to CodeQL https://github.com/dandelion-community/aid-app-monorepo/actions/runs/1580254960

**Comment by lowellbander** [comment]
Do we have an easy way to test whether Latest's mobile builds are working? Is there a better option that looking through https://github.com/dandelion-community/aid-app-monorepo/deployments/activity_log?environment=EAS and clicking the most recent run that was on Latest?

**Comment by bluquar** [comment]
No not that I know of

**Comment by bluquar** [comment]
Abandoning since there's no active need for this
