### ISSUE TITLE
easier local development than manually setting GRAPHQL_URI env var

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#75]
```
GRAPHQL_URI="https://dandelion-community-aid-app-monorepo-4pw54jj2jpxw-3000.githubpreview.dev/graphql"

**Comment by lowellbander** [comment]
oh i don't think setting the env var in this way is even working, perhaps needs to be in `.env` for some reason?

**Comment by bluquar** [comment]
We get access to environment variables in client-side code using [babel-plugin-inline-dotenv](https://www.npmjs.com/package/babel-plugin-inline-dotenv), which is included in our `babel.config.js` on line 5. According to the documentation, all environment variables should be included since `'all'` should be the default value for the `systemVar` setting. However, you could try changing it to `['inline-dotenv', {systemVar: 'all'}]` and see if that fixes it. That should mean that all environment variables should be available, not only those in `.env`.

**Comment by bluquar** [comment]
GRAPHQL_URI no longer needs to be set manually (or at all.)
